# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: 'Misc tags'  


jobs:

  # -------------------------------------------------------------------------------
  #  Bump the semver and update CHANGELOG when doing merges to master
  # -------------------------------------------------------------------------------
  # bump_semver:

  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/master'

  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       token: ${{ secrets.GH_ACTION }}
  #   - name: Bump semver and push tag
  #     uses: TriPSs/conventional-changelog-action@v3
  #     with:
  #       github-token: ${{ secrets.GH_ACTION }}
  #       git-message: 'chore(release): {version}'
  #       preset: 'angular'
  #       tag-prefix: 'v'
  #       output-file: 'CHANGELOG.md'

  # -------------------------------------------------------------------------------
  #  Do a clean build, test, and publish
  # -------------------------------------------------------------------------------
  build:

    # don't run this job until the semver bump has happened
    # if: github.ref == 'refs/heads/master'
      # needs: bump_semver

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Bump semver
      if: github.ref == 'refs/heads/master'
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GH_ACTION }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'

    - name: Pull new semver
      if: github.ref == 'refs/heads/master'
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
      - run: git pull

    - name: Setup .npmrc
      if: github.ref == 'refs/heads/master'
      # Setup .npmrc file to prepare for possible publish to npm
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Build and Test
      uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm test

    - name: Publish
      if: github.ref == 'refs/heads/master'
      uses: actions/checkout@v2
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
